"use client";
import React, { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FaEye, FaEyeSlash } from "react-icons/fa";
import { IoMdClose } from "react-icons/io";
import useAuthStore, { useLoginModalStore } from "@/store/authSlice";
import useAuth from "@/features/auth/hooks/useAuth";

export default function RegiLog() {
  const router = useRouter(); const { user } = useAuthStore(); const { showLoginModal, closeLoginModal } = useLoginModalStore();
  const { login, register, logout, loading } = useAuth(); const [tab, setTab] = useState("login"); const [show, setShow] = useState(false); const [showConfirm, setShowConfirm] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [loginForm, setLoginForm] = useState({ email: "", password: "" }); const [registerForm, setRegisterForm] = useState({ name: "", email: "", password: "", confirm: "" });
  const change = (setter) => (e) => setter((old) => ({ ...old, [e.target.name]: e.target.value }));
  const submitLogin = async (e) => { e.preventDefault(); setError(""); try { const { user: loggedInUser } = await login(loginForm); setMessage("Login successful!"); setTimeout(() => showLoginModal ? closeLoginModal() : router.push(loggedInUser?.role === "admin" ? "/admin/dashboard" : "/dashboard"), 700); } catch (e) { setError(e.message); } };
  const submitRegister = async (e) => { e.preventDefault(); setError(""); if (registerForm.password !== registerForm.confirm) return setError("Passwords do not match"); try { await register({ name: registerForm.name, email: registerForm.email, password: registerForm.password }); setMessage("Account created! Check your email to verify your account."); } catch (e) { setError(e.message); } };
  const doLogout = async () => { try { await logout(); router.push("/"); } catch (e) { setError(e.message); } };
  const field = (name, placeholder, type = "text", form = loginForm, setter = setLoginForm) => <input required type={type} name={name} placeholder={placeholder} value={form[name]} onChange={change(setter)} className="w-full border border-footer px-4 py-4 text-sm" />;
  const passwordField = (name, placeholder, visible, setVisible, form, setter) => <div className="relative"><input required type={visible ? "text" : "password"} name={name} placeholder={placeholder} value={form[name]} onChange={change(setter)} className="w-full border border-footer px-4 py-4 pr-12 text-sm" /><button type="button" aria-label={visible ? "Hide password" : "Show password"} onClick={() => setVisible((value) => !value)} className="absolute right-4 top-1/2 -translate-y-1/2 cursor-pointer text-gray-500">{visible ? <FaEye /> : <FaEyeSlash />}</button></div>;
  const content = <div    className="px-5 max-w-162.75 mx-auto"><div className="flex justify-center gap-10 mb-10"><button type="button" onClick={() => { setTab("login"); setError(""); }} className={`texts_16_medium text-head tracking-widest ${tab === "login" ? "border-b-2 border-head" : "opacity-40"}`}>LOGIN</button><button type="button" onClick={() => { setTab("register"); setError(""); }} className={`texts_16_medium text-head tracking-widest ${tab === "register" ? "border-b-2 border-head" : "opacity-40"}`}>REGISTER</button></div>{message && <div className="bg-green-50 border border-footer text-green-700 px-4 py-3 text-sm mb-5">✅ {message}</div>}{error && <div className="text-xs text-red-500 mb-4">{error}</div>}
    {tab === "login" ? <form onSubmit={submitLogin} className="flex flex-col gap-5">{field("email", "Email address *", "email")}{passwordField("password", "Password *", show, setShow, loginForm, setLoginForm)}<div className="flex justify-end"><Link href="/lost-password" className="texts_14_regular underline">Lost password?</Link></div><button disabled={loading} className="w-full bg-head text-white py-4">{loading ? "LOGGING IN..." : "LOG IN"}</button></form> : <form onSubmit={submitRegister} className="flex flex-col gap-5">{field("name", "Username *", "text", registerForm, setRegisterForm)}{field("email", "Email address *", "email", registerForm, setRegisterForm)}{passwordField("password", "Password *", show, setShow, registerForm, setRegisterForm)}{passwordField("confirm", "Confirm Password *", showConfirm, setShowConfirm, registerForm, setRegisterForm)}<button disabled={loading} className="w-full bg-head text-white py-4">{loading ? "REGISTERING..." : "REGISTER"}</button></form>}</div>;
  if (user && !showLoginModal) return <section><div className="container pt-43 pb-25"><div className="px-5 max-w-162.75 mx-auto text-center"><h2 className="texts_16_medium text-head tracking-widest mb-2">{user.name || "My Account"}</h2><p className="texts_14_regular text-second mb-10">{user.email}</p><button onClick={doLogout} className="w-full bg-head text-white py-4">{loading ? "LOGGING OUT..." : "LOGOUT"}</button></div></div></section>;
  if (showLoginModal) return <div className="fixed inset-0 !z-[99999] flex items-center justify-center bg-black/50" onClick={(e) => e.target === e.currentTarget && closeLoginModal()}><div className="bg-white w-full max-w-md max-h-[90vh] overflow-y-auto relative py-10"><button onClick={closeLoginModal} className="absolute top-4 right-4 text-xl"><IoMdClose /></button>{content}</div></div>;
  return <section><div className="container pt-43 pb-25">{content}</div></section>;
}
